AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Globals:
  Function:
    Runtime: provided
    CodeUri: tests/R/
    Timeout: 300
    MemorySize: 3008
    Layers:
      - !Ref RuntimeLayer
Resources:
  ExampleFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: script.handler
  MatrixFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: matrix.handler
      Layers:
        - !Ref RuntimeLayer
        - !Ref RecommendedLayer
  AWSFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: aws.handler
      Layers:
        - !Ref RuntimeLayer
        - !Ref AWSLayer
  RuntimeLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: runtime
      ContentUri: runtime/build/layer/
  RecommendedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: runtime
      ContentUri: recommended/build/layer/
  AWSLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: runtime
      ContentUri: awspack/build/layer/
